/* eslint-disable @typescript-eslint/no-explicit-any */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kenchoo (https://sketchfab.com/kenchoo)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/okapi-216650e9ec7d4f01a72f7dc0e197361b
Title: Okapi
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props: any) {
	const group = useRef()
	const { nodes, materials }: any = useGLTF('/models/okapi/scene.gltf')
	// const { actions } = useAnimations(animations, group)
	return (
		<group ref={group} {...props} dispose={null}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
					<group name="root">
						<group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
							<group name="skeleton_#0_56">
								<group name="GLTF_created_0">
									<primitive object={nodes.GLTF_created_0_rootJoint} />
									<skinnedMesh
										name="Object_7"
										geometry={nodes.Object_7.geometry}
										material={materials.material_0}
										skeleton={nodes.Object_7.skeleton}
										morphTargetDictionary={nodes.Object_7.morphTargetDictionary}
										morphTargetInfluences={nodes.Object_7.morphTargetInfluences}
									/>
									<group name="NHMW-Zoo1-MAMM_ST348_Okapi_low_res_55" />
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('/models/okapi/scene.gltf')

